[package]
name = "rover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = "0.7"
bevy = {git = "https://github.com/bevyengine/bevy"}
bevy_flycam = "*"
